// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApnQdbN1t_FL4622rHiu0_e9YQAvfjb64',
    appId: '1:461026983064:web:67f235230aa89698faa4ed',
    messagingSenderId: '461026983064',
    projectId: 'whatsapp-4cd27',
    authDomain: 'whatsapp-4cd27.firebaseapp.com',
    storageBucket: 'whatsapp-4cd27.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZ0mGpDVecpLCB5SSXlPODvtYZz8ExzI',
    appId: '1:461026983064:android:5190f0c82aca5092faa4ed',
    messagingSenderId: '461026983064',
    projectId: 'whatsapp-4cd27',
    storageBucket: 'whatsapp-4cd27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjXEWDlDvY30qtYA35wwB30n1NgFcs4c',
    appId: '1:461026983064:ios:c90e6c512ac48e7afaa4ed',
    messagingSenderId: '461026983064',
    projectId: 'whatsapp-4cd27',
    storageBucket: 'whatsapp-4cd27.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvjXEWDlDvY30qtYA35wwB30n1NgFcs4c',
    appId: '1:461026983064:ios:11b67338ca68e545faa4ed',
    messagingSenderId: '461026983064',
    projectId: 'whatsapp-4cd27',
    storageBucket: 'whatsapp-4cd27.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
